param(
    [Alias("Input")]
    [string]$SelfPlayRoot = ".\battle_data\local_fast\trajectories",
    [int]$Checkpoint = 48,
    [string]$SaveDir = ".\cache\selfplay_finetunes",
    [string]$RunName = "synthetic_rl_v2_gen3_selfplay",
    [int]$Epochs = 2,
    [int]$StepsPerEpoch = 250,
    [int]$BatchSizePerGpu = 2,
    [int]$GradAccum = 1,
    [int]$DloaderWorkers = 0
)

$ErrorActionPreference = "Stop"

$SelfPlayRoot = (Resolve-Path $SelfPlayRoot -ErrorAction Stop).Path
$Gen3Root = Join-Path $SelfPlayRoot "*
"
$gen3Dirs = Get-ChildItem $SelfPlayRoot -Directory -ErrorAction SilentlyContinue
if (-not $gen3Dirs) {
    throw "No AMAGO trajectory directories found under $SelfPlayRoot. Run local self-play again after pulling the trajectory-saving update."
}

$yamlDir = Join-Path $PWD "battle_data\selfplay_training"
New-Item -ItemType Directory -Force $yamlDir | Out-Null
$yamlPath = Join-Path $yamlDir "local_selfplay_finetune.yaml"

@"
# Automatically generated by scripts/train_from_selfplay.ps1
# Keep a small amount of the pretrained data distribution while emphasizing
# the newly collected local Gen 3 OU self-play trajectories.
replay_weight: 0.05
prev_dataset: self_play_dset.yaml
prev_weight: 0.75
custom_replays:
  - dir: "$($SelfPlayRoot.Replace('\','/'))"
    weight: 0.20
formats:
  - gen3ou
anneal_epochs: 2
"@ | Set-Content -Encoding UTF8 $yamlPath

Write-Host "Self-play trajectory root: $SelfPlayRoot"
Write-Host "Dataset config: $yamlPath"
Write-Host "Starting SyntheticRLV2 checkpoint $Checkpoint -> finetune run '$RunName'"
Write-Host "Epochs=$Epochs StepsPerEpoch=$StepsPerEpoch BatchSize=$BatchSizePerGpu"

python -m metamon.rl.finetune `
    --run_name $RunName `
    --save_dir $SaveDir `
    --base_model SyntheticRLV2 `
    --base_checkpoint $Checkpoint `
    --dataset_config $yamlPath `
    --train_gin_config finetune.gin `
    --epochs $Epochs `
    --steps_per_epoch $StepsPerEpoch `
    --batch_size_per_gpu $BatchSizePerGpu `
    --grad_accum $GradAccum `
    --dloader_workers $DloaderWorkers `
    --eval_gens 3

if ($LASTEXITCODE -ne 0) {
    throw "SyntheticRLV2 self-play finetuning failed with exit code $LASTEXITCODE."
}

Write-Host ""
Write-Host "Finetuning completed." -ForegroundColor Green
Write-Host "New checkpoints: $SaveDir\$RunName\ckpts\"
Write-Host "Dataset config:  $SaveDir\$RunName\dataset_config.yaml"
