param(
    [Alias("Input")]
    [string]$SelfPlayRoot = ".\battle_data\local_fast\trajectories",
    [int]$Checkpoint = 48,
    [string]$SaveDir = ".\cache\selfplay_finetunes",
    [string]$RunName = "synthetic_rl_v2_gen3_selfplay",
    [int]$Epochs = 2,
    [int]$StepsPerEpoch = 250,
    [int]$BatchSizePerGpu = 2,
    [int]$GradAccum = 1,
    [int]$DloaderWorkers = 0
)

$ErrorActionPreference = "Stop"

$SelfPlayRoot = (Resolve-Path $SelfPlayRoot -ErrorAction Stop).Path
$acceptorRoot = Join-Path $SelfPlayRoot "acceptor"
$challengerRoot = Join-Path $SelfPlayRoot "challenger"
if (-not (Test-Path (Join-Path $acceptorRoot "gen3ou"))) {
    throw "Missing acceptor AMAGO trajectories at $acceptorRoot\gen3ou. Run local self-play again after pulling the trajectory-saving update."
}
if (-not (Test-Path (Join-Path $challengerRoot "gen3ou"))) {
    throw "Missing challenger AMAGO trajectories at $challengerRoot\gen3ou. Run local self-play again after pulling the trajectory-saving update."
}

$yamlDir = Join-Path $PWD "battle_data\selfplay_training"
New-Item -ItemType Directory -Force $yamlDir | Out-Null
$yamlPath = Join-Path $yamlDir "local_selfplay_finetune.yaml"

$acceptorYaml = $acceptorRoot.Replace('\','/')
$challengerYaml = $challengerRoot.Replace('\','/')

@"
# Automatically generated by scripts/train_from_selfplay.ps1
# Keep a small amount of the pretrained distribution while adding newly
# collected Gen 3 OU self-play from both sides of the local match.
replay_weight: 0.05
prev_dataset: self_play_dset.yaml
prev_weight: 0.75
custom_replays:
  - dir: "$acceptorYaml"
    weight: 0.10
  - dir: "$challengerYaml"
    weight: 0.10
formats:
  - gen3ou
anneal_epochs: 2
"@ | Set-Content -Encoding UTF8 $yamlPath

Write-Host "Self-play trajectory root: $SelfPlayRoot"
Write-Host "Dataset config: $yamlPath"
Write-Host "Starting SyntheticRLV2 checkpoint $Checkpoint -> finetune run '$RunName'"
Write-Host "Epochs=$Epochs StepsPerEpoch=$StepsPerEpoch BatchSize=$BatchSizePerGpu"

python -m metamon.rl.finetune `
    --run_name $RunName `
    --save_dir $SaveDir `
    --base_model SyntheticRLV2 `
    --base_checkpoint $Checkpoint `
    --dataset_config $yamlPath `
    --train_gin_config finetune.gin `
    --epochs $Epochs `
    --steps_per_epoch $StepsPerEpoch `
    --batch_size_per_gpu $BatchSizePerGpu `
    --grad_accum $GradAccum `
    --dloader_workers $DloaderWorkers `
    --eval_gens 3

if ($LASTEXITCODE -ne 0) {
    throw "SyntheticRLV2 self-play finetuning failed with exit code $LASTEXITCODE."
}

Write-Host ""
Write-Host "Finetuning completed." -ForegroundColor Green
Write-Host "New checkpoints: $SaveDir\$RunName\ckpts\"
Write-Host "Dataset config:  $SaveDir\$RunName\dataset_config.yaml"
